services:
  redis-simalsi:
    container_name: redis-client-simalsi
    image: docker.io/redis:7
    ports:
      - 6379:6379
    networks:
      - simalsi_network

  # Keycloak
  postgres-keycloak-simalsi:
    container_name: postgres-keycloak-simalsi
    image: docker.io/library/postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      retries: 100

  keycloak-simalsi:
    container_name: keycloak-simalsi
    image: quay.io/keycloak/keycloak:25.0.6
    volumes:
      - "../resources/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: adm1nsimalsi
      KEYCLOAK_ADMIN_PASSWORD: nircut-Bodge0-kacpam
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak-simalsi/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: "true"
    ports:
      - 7777:8080
    restart: always
    depends_on:
      postgres-keycloak-simalsi:
        condition: service_healthy
    networks:
      - keycloak_network
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 5s
      timeout: 10s
      retries: 100

  postgres-simalsi:
    image: docker.io/library/postgres:14
    container_name: postgres-simalsi
    networks:
      - simalsi_network
    environment:
      POSTGRES_DB: simalsi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d simalsi" ]
      interval: 5s
      retries: 100

  simalsi-service:
    image: jguillenl/simalsi-jvm:1.0.0
    container_name: simalsi-service
    network_mode: host
    restart: always
    environment:
      QUARKUS_OIDC_AUTH_SERVER_URL: http://localhost:7777/realms/SIMALSI
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/simalsi
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    depends_on:
      postgres-simalsi:
        condition: service_healthy
      keycloak-simalsi:
        condition: service_healthy

  simalsi-nuxt:
    image: jguillenl/simalsi-nuxt:1.0.0
    container_name: simalsi-nuxt
    network_mode: host
    restart: always
    environment:
      NUXT_SESSION_PASSWORD: 22357648e74e4975a8375d0f7982cfe0
      NUXT_API_BASE: http://localhost:8080/api
      NUXT_PUBLIC_APP_BASE: http://localhost:3000
      NUXT_OAUTH_KEYCLOAK_SERVER_URL: http://localhost:8180
      NUXT_OAUTH_KEYCLOAK_CLIENT_ID: http://localhost:3000
      NUXT_OAUTH_KEYCLOAK_CLIENT_SECRET: http://localhost:3000
      NUXT_OAUTH_KEYCLOAK_REALM: SIMALSI
    depends_on:
      keycloak-simalsi:
        condition: service_healthy

networks:
  keycloak_network:
    driver: bridge
  simalsi_network:
    driver: bridge
