services:
  # Keycloak
  postgres-keycloak-simalsi:
    container_name: postgres-keycloak-simalsi
    image: docker.io/library/postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak -d keycloak" ]
      interval: 5s
      retries: 100

  keycloak-simalsi:
    container_name: keycloak-simalsi
    image: quay.io/keycloak/keycloak:25.0.6
    volumes:
      - "../resources/keycloak/realm-export.json:/opt/keycloak/data/import/car-rental-realm.json"
      - "../resources/keycloak/kcthemes/themes:/opt/keycloak/themes"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak-simalsi/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: "true"
    ports:
      - 7777:8080
    restart: always
    depends_on:
      postgres-keycloak-simalsi:
        condition: service_healthy
    networks:
      - keycloak_network
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 5s
      timeout: 10s
      retries: 100

  postgres-simalsi:
    image: docker.io/library/postgres:14
    container_name: postgres-simalsi
    networks:
      - simalsi_network
    environment:
      POSTGRES_DB: simalsi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d simalsi" ]
      interval: 5s
      retries: 100

  simalsi-service:
    image: quarkus/simalsi-jvm:latest
    container_name: simalsi-service
    network_mode: host
    restart: always
    depends_on:
      postgres-simalsi:
        condition: service_healthy
      keycloak-simalsi:
        condition: service_healthy

networks:
  keycloak_network:
    driver: bridge
  simalsi_network:
    driver: bridge